<?php

namespace Kendoctor\Bundle\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChoiceItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoiceItemRepository extends EntityRepository
{
}
