<?php

namespace Kendoctor\Bundle\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaperRepository extends EntityRepository {

    /**
     * 获取已经发布的试卷 
     * 
     */
    public function getPublishedPapers() {
        return $this->_em->createQuery("
           SELECT p 
           FROM KendoctorTestBundle:Paper p
     
        ")->getResult();
        //      WHERE p.isPublished = true
    }

    public function getPaperById() {
        
    }

    public function getPaperWithAllItemsById($id) {
        return $this->_em->createQuery("
           SELECT p
           FROM KendoctorTestBundle:Paper p
           
           WHERE p.id = :id
        ")
        ->setParameter("id", $id)
        ->getOneOrNullResult();
    }
    
    /**
     *LEFT JOIN p.ItemGroups ig
           LEFT JOIN ig.ItemGroupItems igi
           LEFT JOIN igi.ChoiceItem ci
           LEFT JOIN ci.ChoiceItemAnswers cia 
     */

}
